#################################################################################################
# This is the properties file for the Minecraft Server Launcher
# Complete this file to run the launcher correctly
#################################################################################################
#Display Server Name (Optional)
server-name=
# Minimum & Maximum Ram
# Example: 512M / 8G
# M=Megabyte
# G=Gigabyte
min-ram=
max-ram=
# Specify Java Directory (No need to specify if you want to use the default Java)
# Use a directory like this (Windows): C:\Program Files\Java\jdk-xx
custom-jdk=
# Auto-restart feature
# Set to true to enable auto-restart
auto-restart=

